int PLAYER_HP_MAX = 100;
int PLAYER_MP_MAX = 100;
int PLAYER_DEFAULT_ATK = 50;
int PLAYER_DEFAULT_DEF = 10;

int ZERGLING_HP_MAX = 80;
int	ZERGLING_MP_MAX = 0;
int	ZERGLING_ATK = 20;
int	ZERGLING_DEF = 0;